config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end 

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_contact.html.erb
<section class="contact">
  <h2>Kontakt</h2>
    <hr>
    <form action="">
      <input type="text" name="" id="" placeholder="Imię">
      <input type="email" name="" id="" placeholder="Emial">
      <textarea name="" id="" placeholder="Wiadomość"></textarea>
    </form>
      <a href="" class="btn">Wyślij wiadomość</a>
      <div>
      <iframe src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2Flucasproboxing&tabs&width=340&height=181&small_header=false&adapt_container_width=false&hide_cover=false&show_facepile=true&appId" width="340" height="181" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true" allow="encrypted-media"></iframe>
      </div>
</section>

app/views/home/_footer.html.erb
<footer>
  <p>Copyright &copy; Lucas Pro Boxing - Coach</p>
</footer>

app/views/home/_header.html.erb
<nav class="navbar navbar-default navbar-expand-lg navbar-light sticky-top nav-fill">
			<div class="navbar-header d-flex col">
				<a class="navbar-brand" href="#"><b><%= link_to 'Lucas Pro Boxing', home_index_path %></b></a>  		
				<button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle navbar-toggler ml-auto">
					<span class="navbar-toggler-icon"></span>
					<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			</div>
			<!-- Collection of nav links, forms, and other content for toggling -->
			<div id="navbarCollapse" class="collapse navbar-collapse justify-content-start">
				<ul class="nav navbar-nav">
					<li class="nav-item"><a href="#" class="nav-link"><%= link_to 'O mnie', home_about_path %></a></li>
								
					<li class="nav-item dropdown">
						<a data-toggle="dropdown" class="nav-link dropdown-toggle active" href="#">Trenuj online</a>
						<ul class="dropdown-menu">					
							<li><a href="#" class="dropdown-item">Boxing</a></li>
							<li><a href="#" class="dropdown-item">Weight loss</a></li>
							<li><a href="#" class="dropdown-item">HIT</a></li>
							<li><a href="#" class="dropdown-item">Endurance</a></li>
							<li><a href="#" class="dropdown-item">TRENING ONLINE</a></li>
						</ul>
					</li>
					<li class="nav-item"><a href="#" class="nav-link">Aktualności</a></li>
					<li class="nav-item"><a href="#" class="nav-link">Cennik</a></li>
					<li class="nav-item"><a href="#" class="nav-link">Kontakt</a></li>
							
								<li class="nav-item"><a class="nav-link" href="https://www.facebook.com/lucasproboxing/"><i class="fa fa-facebook-square"></i></a></li>
								<li class="nav-item"><a class="nav-link" href="https://www.youtube.com/channel/UCwKGb7J16RojxwIhRPo_JIw/videos"><i class="fa fa-youtube"></i></a></li>
				</ul>
				
				<ul class="nav navbar-nav navbar-right ml-auto">			
					<li class="nav-item">
						<a data-toggle="dropdown" class="nav-link dropdown-toggle" href="#">Login</a>
						<ul class="dropdown-menu form-wrapper">					
							<li>
								<form action="/examples/actions/confirmation.php" method="post">
									<p class="hint-text">Sign in with your social media account</p>
									<div class="form-group social-btn clearfix">
										<a href="#" class="btn btn-primary pull-left"><i class="fa fa-facebook"></i> Facebook</a>
										<a href="#" class="btn btn-danger pull-right"><i class="fa fa-google"></i> Google</a>
									</div>
									<div class="or-seperator"><b>or</b></div>
									<div class="form-group">
										<input type="text" class="form-control" placeholder="Username" required="required">
									</div>
									<div class="form-group">
										<input type="password" class="form-control" placeholder="Password" required="required">
									</div>
									<input type="submit" class="btn btn-primary btn-block" value="Login">
									<div class="form-footer">
										<a href="#" style="font-size: small;">Forgot Your password?</a>
									</div>
								</form>
							</li>
						</ul>
					</li>
					<li class="nav-item">
						<a href="#" data-toggle="dropdown" class="btn btn-primary dropdown-toggle get-started-btn mb-1">Sign up</a>
						<ul class="dropdown-menu form-wrapper">					
							<li>
								<form action="/examples/actions/confirmation.php" method="post">
									<p class="hint-text">Fill in this form to create your account!</p>
									<div class="form-group">
										<input type="text" class="form-control" placeholder="Username" required="required">
									</div>
									<div class="form-group">
										<input type="password" class="form-control" placeholder="Password" required="required">
									</div>
									<div class="form-group">
										<input type="password" class="form-control" placeholder="Confirm Password" required="required">
									</div>
									<div class="form-group">
										<label class="checkbox-inline"><input type="checkbox" required="required"> I accept the <a href="#" style="font-size:small;">Privacy&amp; political</a></label>
									</div>
									<input type="submit" class="btn btn-primary btn-block" value="Sign up">
								</form>
							</li>
						</ul>
					</li>
				</ul>
			</div>
		</nav>

app/views/home/_slide.html.erb
<section class="slide">
  <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img class="d-block w-30" src="../images/img/boxing.png" alt="First slide">
        </div>
        <div class="carousel-item">
          <img class="d-block w-30" src="LucasProBoxing/app/assets/images/boxing-glove-stock-photography-stock-xchng-gloves-png-clipart.jpg" alt="Second slide">
        </div>
        <div class="carousel-item">
          <img class="d-block w-30" src="/home/sylwiab/PROJECTS/Boxing/LucasProBoxing/app/assets/images/boxing-glove-kickboxing-muay-thai-punch-combat-silhouette-martial-arts-professional-boxer-png-clip-art.png" alt="Third slide">
        </div>
        <div class="carousel-item">
          <img class="d-block w-30" src="../boxing/css/2cd43b_7d166629b2f147faa77bd5b2b514173b_mv2.pn" alt="First slide">
        </div>
        <div class="carousel-item">
          <img class="d-block w-30" src="../boxing/css/163-1632473_kick-boxing-png-transparent-png.png" alt="Second slide">
        </div>
        <div class="carousel-item">
          <img class="d-block w-30" src="../boxing/css/boxing-png-21.png" alt="Third slide">
        </div>
      </div>
  </div>
</section>

app/views/home/about.html.erb
<section class="about">
  <h2>O mnie </h2>
    <hr>
      <img src="../images/img/kick-boxing-transparent.png"  alt="Boxing">

        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quae dolorem ut aliquid? Itaque adipisci maxime ut nam illo ducimus voluptas harum ad laborum nihil? Repellendus dolorum delectus aut hic fugit?</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad provident dignissimos doloribus dolorem quam sed enim excepturi autem saepe, optio nemo. Iusto laboriosam porro, sapiente unde consequatur itaque quisquam alias?
        </p>

  </section>

  <section id="nayma-timeline" class="nayma-container">
    <div class="nayma-timeline-block">
      <div class="nayma-timeline-img">
      </div>
        <div class="nayma-timeline-content">
          <h2>Rok 2005</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, optio, dolorum provident rerum aut hic quasi placeat iure tempora laudantium ipsa ad debitis unde? Iste voluptatibus minus veritatis qui ut.</p>
        </div>
    </div>
    <div class="nayma-timeline-block">
      <div class="nayma-timeline-img">
      </div>
        <div class="nayma-timeline-content">
          <h2>Rok 2007</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, optio, dolorum provident rerum aut hic quasi placeat iure tempora laudantium ipsa ad debitis unde?</p>
        </div>
      </div>
      <div class="nayma-timeline-block">
        <div class="nayma-timeline-img">
          </div>
          <div class="nayma-timeline-content">
            <h2>Rok 2009</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi, obcaecati, quisquam id molestias eaque asperiores voluptatibus cupiditate error assumenda delectus odit similique earum voluptatem doloremque dolorem ipsam quae rerum
                quis. Odit, itaque, deserunt corporis vero ipsum nisi eius odio natus ullam provident pariatur temporibus quia eos repellat consequuntur perferendis enim amet quae quasi repudiandae sed quod veniam dolore possimus rem voluptatum eveniet
                eligendi quis fugiat aliquam sunt similique aut adipisci.</p>
          </div>
      </div>
      <div class="nayma-timeline-block">
        <div class="nayma-timeline-img">
        </div>
          <div class="nayma-timeline-content">
            <h2>Rok 2010</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, optio, dolorum provident rerum.</p>
          </div>
      </div>
      <div class="nayma-timeline-block">
        <div class="nayma-timeline-img">
        </div>
          <div class="nayma-timeline-content">
            <h2>Rok 2015</h2>
              <p>This is the content of the last section</p>
          </div>
      </div>
    </section>

    

app/views/home/index.html.erb
    
    <%= yield %>

   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LucasProBoxing</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
    <link rel="shortcut icon" href="../favicon-96x96.png">
    <link rel="stylesheet" href="">
     
    <script type="text/javascript">
		// Prevent dropdown menu from closing when click inside the form
			$(document).on("click", ".navbar-right .dropdown-menu", function(e){
				e.stopPropagation();
			});
    </script>
    

  </head>

  <body>
     
		<%= render 'home/header' %>
    

		<%= yield %>
		<%= render 'home/slide' %>
		<%= render 'home/contact' %>
  	<%= render 'home/footer' %>



    <%# <button type="button" data-toggle="collapse" data-target="#style-switch" id="style-switch-button" class="btn btn-outline-danger btn-sm d-none d-lg-block"><i class="fa fa-youtube fa-2x"></i></button>
    <br> <br>
    <button type="button" data-toggle="collapse" data-target="#style-switch" id="style-switch-button" class="btn btn-primary btn-sm d-none d-lg-block"><i class="fa fa-facebook-square fa-2x"></i></button>
    <br><br> %>
   

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://d19m59y37dris4.cloudfront.net/sell/1-3-1/vendor/jquery/jquery.min.js"></script>
    
  </body>
</html>